const { chromium } = require('playwright');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const base = process.env.BASE_URL || 'http://127.0.0.1:8000';
const output = path.resolve('test-results');
fs.mkdirSync(output, {recursive:true});
const username = `e2e_${Date.now().toString(36)}`;
const password = `Journey!${crypto.randomUUID()}`;
const errors=[];
async function noOverflow(page,label) {
 const sizes=await page.evaluate(()=>({width:innerWidth,scroll:document.documentElement.scrollWidth}));
 assert.ok(sizes.scroll<=sizes.width, `${label} overflow: ${JSON.stringify(sizes)}`);
}
(async()=>{
 const browser=await chromium.launch({headless:true});
 const context=await browser.newContext({viewport:{width:1440,height:1000}});
 const page=await context.newPage();
 page.on('pageerror',error=>errors.push(error.message));
 page.on('dialog',dialog=>dialog.accept());
 try {
  await page.goto(base);
  await page.locator('img').evaluateAll(images=>Promise.all(images.map(image=>{image.loading='eager';return image.decode();})));
  assert.equal(await page.locator('.route-card').count(),6);
  assert.deepEqual(await page.locator('img').evaluateAll(imgs=>imgs.filter(i=>!i.complete||!i.naturalWidth).map(i=>i.src)),[]);
  await page.screenshot({path:path.join(output,'home-desktop.png'),fullPage:true});
  await page.setViewportSize({width:390,height:844});
  await noOverflow(page,'mobile home');
  await page.screenshot({path:path.join(output,'home-mobile.png'),fullPage:true});
  await page.goto(base+'/routes/');
  assert.equal(await page.locator('.route-card').count(),18);
  await page.getByRole('link',{name:'下一页 →',exact:true}).click();
  assert.equal(await page.locator('.route-card').count(),12);
  await page.goto(base+'/routes/?q='+encodeURIComponent('皖南'));
  await page.locator('.route-title').first().click();
  await page.getByRole('link',{name:'用这条路线开始规划 ↗'}).click();
  await page.waitForURL('**/accounts/login/**');
  await noOverflow(page,'mobile login');
  await page.getByRole('link',{name:'免费注册',exact:true}).click();
  await page.locator('[name=username]').fill(username);
  await page.locator('[name=password1]').fill(password);
  await page.locator('[name=password2]').fill(password);
  await page.getByRole('button',{name:'创建账号，出发 →'}).click();
  await page.waitForURL('**/plan/new/**');
  fs.writeFileSync(path.join(output,'created-test-user.json'),JSON.stringify({username}));
  assert.match(await page.locator('#trip-title').inputValue(),/皖南/);
  assert.ok(await page.locator('.stop-card').count()>0,'selected template survives signup');
  await noOverflow(page,'mobile editor');
  await page.locator('#trip-title').fill('皖南山野 · 周末慢旅行');
  await page.locator('#trip-mode').selectOption('ev');
  await page.locator('#trip-range').fill('220');
  await page.locator('#trip-budget').fill('2380.50');
  await page.locator('#trip-start-date').fill('2026-10-02');
  await page.locator('#add-stop').click();
  await page.locator('[data-kind=hotel]').click();
  await page.getByText('手动添加地点 / 编辑坐标',{exact:true}).click();
  await page.locator('#manual-place-form [name=name]').fill('湖畔小住 · 自定义住宿');
  await page.locator('#manual-place-form [name=lng]').fill('118.475');
  await page.locator('#manual-place-form [name=lat]').fill('30.633');
  await page.locator('#manual-place-form [name=note]').fill('测试行程：预订前确认入住条件');
  await page.getByRole('button',{name:'添加到当天行程 ＋'}).click();
  assert.equal(await page.locator('.stop-card.hotel').count(),1);
  await page.locator('#save-trip').click();
  await page.waitForURL(/\/trips\/[^/]+\/edit\//);
  await page.getByText('已保存到账号',{exact:true}).waitFor();
  await page.reload();
  assert.equal(await page.locator('#trip-budget').inputValue(),'2380.50');
  assert.equal(await page.locator('#trip-mode').inputValue(),'ev');
  assert.equal(await page.locator('.stop-card.hotel').count(),1);
  await page.locator('#calculate-trip').click();
  await page.getByText('当前结果为直线估算，详细说明见地图下方。',{exact:true}).waitFor();
  assert.match(await page.locator('#route-warnings').textContent(),/20%/);
  assert.ok(await page.locator('.editor-map-panel').isVisible());
  await noOverflow(page,'mobile calculated map');
  await page.screenshot({path:path.join(output,'editor-mobile-map.png'),fullPage:true});
  await page.locator('[data-view=list]').click();
  await page.locator('[data-day="2"]').click();
  await page.locator('.origin-bridge').getByText(/湖畔小住/).waitFor();
  await page.screenshot({path:path.join(output,'editor-mobile-list.png'),fullPage:true});
  await page.setViewportSize({width:1440,height:1000});
  await noOverflow(page,'desktop editor');
  await page.screenshot({path:path.join(output,'editor-desktop.png'),fullPage:true});
  await page.locator('#view-trip').click();
  await page.waitForURL(url=>!url.pathname.endsWith('/edit/'));
  await page.getByRole('heading',{name:'皖南山野 · 周末慢旅行',exact:true}).waitFor();
  const privateUrl=page.url();
  const outsider=await browser.newContext();
  const visitor=await outsider.newPage();
  assert.equal((await visitor.goto(privateUrl)).status(),404);
  const downloadPromise=page.waitForEvent('download');
  await page.getByRole('link',{name:'↓ 导出 JSON 行程'}).click();
  const download=await downloadPromise;
  const jsonPath=path.join(output,'exported.json');await download.saveAs(jsonPath);
  const exported=JSON.parse(fs.readFileSync(jsonPath,'utf8'));
  assert.equal(exported.coordinate_system,'GCJ-02');assert.equal(exported.budget,'2380.50');
  await page.getByRole('button',{name:'公开分享路线',exact:true}).click();
  await page.getByRole('button',{name:'改为私密',exact:true}).waitFor();
  assert.equal((await visitor.goto(privateUrl)).status(),200);
  await visitor.getByRole('link',{name:'登录后复制这份旅行 ↗'}).click();
  await visitor.waitForURL('**/accounts/login/**');
  await page.getByRole('button',{name:'改为私密',exact:true}).click();
  assert.equal((await visitor.goto(privateUrl)).status(),404);
  await outsider.close();
  await page.goto(base+'/import/');
  await page.locator('input[type=file]').setInputFiles(jsonPath);
  await page.getByRole('button',{name:'导入并开始编辑 ↗'}).click();
  await page.waitForURL(/\/trips\/[^/]+\/edit\//);
  assert.equal(await page.locator('#trip-title').inputValue(),exported.title);
  assert.equal(await page.locator('#trip-range').inputValue(),'220');
  // Unsaved conflict and network failures preserve the current editor contents.
  if(!await page.locator('#trip-title').isVisible()) await page.locator('.trip-settings summary').click();
  await page.locator('#trip-title').fill('冲突时保留我的修改');
  await page.route('**/api/trips/*/save/',route=>route.fulfill({status:409,contentType:'application/json',body:JSON.stringify({ok:false,error:'其他设备已修改，请刷新后重试。'})}));
  await page.locator('#save-trip').click();
  await page.getByText('其他设备已修改，请刷新后重试。',{exact:true}).waitFor();
  assert.equal(await page.locator('#trip-title').inputValue(),'冲突时保留我的修改');
  await page.unroute('**/api/trips/*/save/');
  await page.locator('#save-trip').click();
  await page.getByText('已保存到账号',{exact:true}).waitFor();
  // The editor supports changing stop order, moving stops to another day, and removing stops.
  await page.locator('[data-day="1"]').click();
  const firstName=await page.locator('.stop-card h3').first().textContent();
  await page.locator('.stop-card').first().getByRole('button',{name:new RegExp('^下移')}).click();
  assert.notEqual(await page.locator('.stop-card h3').first().textContent(),firstName);
  const beforeCount=await page.locator('.stop-card').count();
  await page.locator('.stop-card-actions select').first().selectOption('2');
  assert.equal(await page.locator('.stop-card').count(),beforeCount-1);
  await page.locator('.stop-card').first().getByRole('button',{name:new RegExp('^移除')}).click();
  assert.equal(await page.locator('.stop-card').count(),beforeCount-2);
  await page.locator('#save-trip').click();await page.getByText('已保存到账号',{exact:true}).waitFor();
  await page.goto(base+'/my-trips/');
  await page.setViewportSize({width:390,height:844});
  await noOverflow(page,'mobile saved trips');
  await page.getByRole('button',{name:'退出登录',exact:true}).click();
  await page.waitForURL(base+'/');
  assert.deepEqual(errors,[]);
  console.log(JSON.stringify({ok:true,username,checks:['30 routes/pagination','guest template + signup','mobile layout','hotel linkage','EV estimates','save/reload + decimals','private authorization','publish/unpublish','JSON export/import','save conflict preserves edits','reorder/move/remove','mobile logout'],screenshots:output}));
 } finally {await browser.close();}
})().catch(error=>{console.error(error);process.exit(1)});
