# Generated by Django 5.2.17 on 2026-09-22 09:55

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RouteTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='路线标识')),
                ('title', models.CharField(max_length=120, verbose_name='路线名称')),
                ('subtitle', models.CharField(blank=True, max_length=180, verbose_name='一句话介绍')),
                ('region', models.CharField(db_index=True, max_length=40, verbose_name='地区')),
                ('category', models.CharField(db_index=True, default='classic', max_length=40, verbose_name='主题')),
                ('days', models.PositiveSmallIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(30)], verbose_name='建议天数')),
                ('distance_km', models.PositiveIntegerField(default=0, verbose_name='参考公里数')),
                ('season', models.CharField(blank=True, max_length=80, verbose_name='建议季节')),
                ('difficulty', models.CharField(default='轻松', max_length=40, verbose_name='行程强度')),
                ('description', models.TextField(blank=True, max_length=10000, verbose_name='路线介绍')),
                ('tags', models.JSONField(blank=True, default=list, verbose_name='特色标签')),
                ('stops', models.JSONField(blank=True, default=list, verbose_name='途经地点')),
                ('cover_style', models.CharField(default='mountain', max_length=40, verbose_name='封面样式')),
                ('featured', models.BooleanField(db_index=True, default=False, verbose_name='首页推荐')),
                ('source_notes', models.TextField(blank=True, verbose_name='信息来源与注意事项')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '精选路线',
                'verbose_name_plural': '精选路线',
                'ordering': ['-featured', 'title'],
                'constraints': [models.CheckConstraint(condition=models.Q(('days__gte', 1), ('days__lte', 30)), name='route_days_in_range')],
            },
        ),
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_bookmarks', to=settings.AUTH_USER_MODEL)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='planner.routetemplate')),
            ],
            options={
                'verbose_name': '路线收藏',
                'verbose_name_plural': '路线收藏',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('user', 'route'), name='unique_user_route_bookmark')],
            },
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(default='我的新旅行', max_length=120, verbose_name='行程名称')),
                ('description', models.TextField(blank=True, max_length=10000, verbose_name='行程介绍')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='出发日期')),
                ('days', models.PositiveSmallIntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(30)], verbose_name='旅行天数')),
                ('travel_mode', models.CharField(choices=[('driving', '自驾'), ('ev', '新能源自驾'), ('walking', '步行'), ('cycling', '骑行')], default='driving', max_length=12, verbose_name='出行方式')),
                ('budget', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(Decimal('99999999.99'))], verbose_name='预算（元）')),
                ('ev_range_km', models.PositiveSmallIntegerField(default=400, validators=[django.core.validators.MinValueValidator(50), django.core.validators.MaxValueValidator(1200)], verbose_name='车辆满电续航（公里）')),
                ('is_public', models.BooleanField(default=False, verbose_name='公开分享')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('published', '已发布')], default='draft', max_length=12, verbose_name='状态')),
                ('stops', models.JSONField(blank=True, default=list, verbose_name='途经地点')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
            ],
            options={
                'verbose_name': '用户行程',
                'verbose_name_plural': '用户行程',
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['is_public', 'status', '-updated_at'], name='trip_community_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('days__gte', 1), ('days__lte', 30)), name='trip_days_in_range'), models.CheckConstraint(condition=models.Q(('budget__gte', 0)), name='trip_budget_nonnegative'), models.CheckConstraint(condition=models.Q(('ev_range_km__gte', 50), ('ev_range_km__lte', 1200)), name='trip_ev_range_in_range'), models.CheckConstraint(condition=models.Q(models.Q(('is_public', False), ('status', 'draft')), models.Q(('is_public', True), ('status', 'published')), _connector='OR'), name='trip_public_status_consistent')],
            },
        ),
    ]
